### ISSUE TITLE
not working in redmine 5.0.3 ruby 3.1.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [RedminePower/redmine_reply_button#2]
```
redmine@redmine:/var/www/5.0.2$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- that_issue_reply_button_hook
/var/www/5.0.2/plugins/redmine_reply_button/init.rb:3:in `<top (required)>'
/var/www/5.0.2/lib/redmine/plugin_loader.rb:31:in `load'
/var/www/5.0.2/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/var/www/5.0.2/lib/redmine/plugin_loader.rb:108:in `each'
/var/www/5.0.2/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/www/5.0.2/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by SabastianGambrell** [comment]
Thanks for the report.
Fixed by @RedminePower pull request.
